apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      svc-name: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        svc-name: {{ .Values.deployment.name }}
    spec:
      containers:
      - image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Values.deployment.name }}
        env:
        - name: WORLD
          value: {{ .Values.deployment.world }}
